In [1]:
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D, Convolution2D
from keras.layers.core import Activation
from keras.layers.core import Flatten
from keras.layers.core import Dropout
from keras.layers.core import Dense
from keras.optimizers import SGD,RMSprop,adam,Adam,Adagrad
from keras import backend as K
import matplotlib.pyplot as plt
import os
import theano
from PIL import Image
from sklearn.utils import shuffle
from sklearn.cross_validation import train_test_split
import matplotlib
import cv2
from keras.utils import np_utils
import numpy as np
from numpy import *
from tqdm import tqdm
import glob as glob
import imutils

from keras.optimizers import Adam

C:\Users\Harsh Pande\AppData\Local\Continuum\anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
C:\Users\Harsh Pande\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
#p1 = "C:/Users/Harsh Pande/Desktop/Final Dataset"
p1 = "C:/Users/Harsh Pande/Desktop/Final & Flipped Dataset/"
#p2 = "C:/Users/prana/Desktop/DataScience/processed"
img_rows = 50
img_cols = 50

In [3]:
imglist = os.listdir(p1)

In [4]:
n_samples = len(imglist)
print(n_samples)

17400


In [5]:
'''files = glob.glob ("C:/Users/Harsh Pande/Desktop/Final Dataset/*.jpg")
i = 0
for myFile in files:
    image = cv2.imread (myFile)
    mirror_img = np.fliplr(image)
    #rotated = imutils.rotate(image, 270)
    path = 'C:/Users/prana/Desktop/DataScience/flipped'
    cv2.imwrite(os.path.join(path , "img"+str(i)+".jpg"), mirror_img)
    i = i + 1
'''

'files = glob.glob ("C:/Users/Harsh Pande/Desktop/Final Dataset/*.jpg")\ni = 0\nfor myFile in files:\n    image = cv2.imread (myFile)\n    mirror_img = np.fliplr(image)\n    #rotated = imutils.rotate(image, 270)\n    path = \'C:/Users/prana/Desktop/DataScience/flipped\'\n    cv2.imwrite(os.path.join(path , "img"+str(i)+".jpg"), mirror_img)\n    i = i + 1\n'

In [6]:
#
import cv2
import glob
import numpy as np

X_data = []
files = glob.glob ("C:/Users/Harsh Pande/Desktop/Final & Flipped Dataset/*.jpg")
for myFile in files:
    #print(myFile)
    image = cv2.imread (myFile)
    resized_image = cv2.resize(image, (img_rows,img_cols)) 
    X_data.append (resized_image)

final = np.array(X_data)
final.shape

(17400, 50, 50, 3)

In [7]:
pixel_lists = final.reshape(final.shape[:-3] + (-1, 3))
print(pixel_lists.shape)  

new1 = pixel_lists.reshape((pixel_lists.shape[1]*pixel_lists.shape[2]),pixel_lists.shape[0])
print(new1.shape)
new2 = new1.transpose()
print(new2.shape)



(17400, 2500, 3)
(7500, 17400)
(17400, 7500)


In [8]:
label = np.ones((n_samples,),dtype = int)
label[0:5799] = 0
label[5800:11599] = 1
label[11600:17399] = 2
print(label[2799])

0


In [9]:
data, Label =shuffle(new2,label,random_state=2)
train_data = [data, Label]


In [10]:
print(train_data[0].shape)
print(train_data[1].shape)
print(train_data[0][2][-300:])

(17400, 7500)
(17400,)
[255  20  58 255 103  69 255  36 120   0 121 222 255 189  42 177 252  28
  94 255 118   1 255 122 185 255 123  45   0 154  95 255  49  68 255  59
  61 254 182  52 118 251 150 193 255 174  38 255  84  43 255  73 128 255
 121  82 255 162  35 255  62  60 253  43 147 189 253  96  42 255  58 170
 255  62  29 255  24  86 255  54  80 255 108  38 255  24  79 255  56  75
 255 253 149 199 254  77  99 255  85  73   0  49 155   0  69  73   0  72
 137   0 117 139 253  13 129  71 255 123  44 168 111  44   0 111  80   0
  60  72   0 127  73   0  69  56 255  42 110 254  42 135 250 253 122  51
   0  96 192   0  98  92   0 211 107   0  11 175   0 144 112   0  30  95
 255 219 104 237 255 178  52   0  63 163   0 166  95   0 124  87   0  82
 182   0 102  55   0  43  46 254 115  99  75 253  95  16 255  89 159   0
  70 132   0  91 129   0 168 148   0  73 190   0  31 190 255  14 117 181
 255  85  30 255 163  84   0 154 157   0 150 197   0 170 105   0  82  24
   0  94  94   0 253 186  64

In [11]:
#Parameters
batch_size = 256
n_epochs = 10
n_classes = 3
img_channel = 3
n_filters = 128
n_filters2 = 64
n_filters3 = 32
n_pool = 2
n_conv = 3

In [12]:
(x , y) = (train_data[0],train_data[1])
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.45,random_state=33)


x_train = x_train.reshape(x_train.shape[0],3,img_rows,img_cols)

x_test = x_test.reshape(x_test.shape[0],3,img_rows,img_cols)



x_train = x_train.astype('float32')
x_test = x_test.astype('float32')


x_train /= 255#standardization
x_test /= 255

y_train = np_utils.to_categorical(y_train,n_classes)
y_test = np_utils.to_categorical(y_test,n_classes)

print(y_train)


[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 ...
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [13]:
#changes1 ===> n_filters, activation,dropout

In [14]:
model  = Sequential()
'''
K.set_image_dim_ordering('th')
model.add(Convolution2D(32,(3,3), input_shape=(3,img_rows,img_cols)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))


model.add(Convolution2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))


model.add(Convolution2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(n_classes))

model.add(Activation('sigmoid'))
model.compile(loss='categorical_crossentropy', optimizer='adam',metrics=['accuracy'])

'''

K.set_image_dim_ordering('th')
model.add(Convolution2D(n_filters3,n_conv,n_conv,border_mode='valid',input_shape=(3,img_rows,img_cols)))#n_filters should be in power of 2
convout1 = Activation('relu')
model.add(convout1)
model.add(MaxPooling2D(pool_size=(n_pool,n_pool),dim_ordering="th"))
#model.add(Dropout(0.2))#0.119

model.add(Convolution2D(n_filters3,n_conv,n_conv))
convout2 = Activation('relu')#(0,x) if x is neg it will be 0 else whatever is the value of x
model.add(convout2)
model.add(MaxPooling2D(pool_size=(n_pool,n_pool),dim_ordering="th"))
#model.add(Dropout(0.2))

model.add(Convolution2D(n_filters3,n_conv,n_conv))
convout2 = Activation('relu')
model.add(convout2)
model.add(MaxPooling2D(pool_size=(n_pool,n_pool),dim_ordering="th"))
#model.add(Dropout(0.2))

model.add(Convolution2D(n_filters3,n_conv,n_conv))
convout2 = Activation('relu')
model.add(convout2)
model.add(MaxPooling2D(pool_size=(n_pool,n_pool),dim_ordering="th"))
#model.add(Dropout(0.2))


model.add(Flatten())
#model.add(Dense(32))   ###Changes
model.add(Activation('relu'))
#model.add(Dropout(0.25))


model.add(Dense(n_classes))  ###Changes
#model.add(Activation('relu'))

#model.add(Dropout(0.5))##changed position

model.add(Activation('softmax'))#e to power of x/summation of e to the power of x(basically gives us the probability)


#keras.optimizers.Adam(lr=0.001, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0, amsgrad=False)
optimizer = Adam()
model.compile(loss='categorical_crossentropy',optimizer=optimizer ,metrics=['accuracy'])
#keras.optimizers.Adagrad(lr=0.01, epsilon=None, decay=0.0)
model.summary()

C:\Users\Harsh Pande\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:30: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3), input_shape=(3, 50, 50..., padding="valid")`
C:\Users\Harsh Pande\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:33: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D(pool_size=(2, 2), data_format="channels_first")`
C:\Users\Harsh Pande\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:36: UserWarning: Update your `Conv2D` call to the Keras 2 API: `Conv2D(32, (3, 3))`
C:\Users\Harsh Pande\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:39: UserWarning: Update your `MaxPooling2D` call to the Keras 2 API: `MaxPooling2D(pool_size=(2, 2), data_format="channels_first")`
C:\Users\Harsh Pande\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:42: UserWarning: Update your `Conv2D` call to the

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 32, 48, 48)        896       
_________________________________________________________________
activation_1 (Activation)    (None, 32, 48, 48)        0         
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 32, 24, 24)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 32, 22, 22)        9248      
_________________________________________________________________
activation_2 (Activation)    (None, 32, 22, 22)        0         
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 32, 11, 11)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 32, 9, 9)          9248      
__________

In [15]:
history = model.fit(x_train,y_train,batch_size=batch_size,epochs=n_epochs,verbose=1,validation_data=(x_test,y_test))
# list all data in history
'''print(history.history.keys())
# summarize history for accuracy
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()
# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()'''

Train on 9570 samples, validate on 7830 samples
Epoch 1/10
9570/9570 [==============================] - ETA: 1:36 - loss: 1.1016 - acc: 0.316 - ETA: 1:24 - loss: 1.1040 - acc: 0.318 - ETA: 1:18 - loss: 1.1026 - acc: 0.312 - ETA: 1:17 - loss: 1.1034 - acc: 0.312 - ETA: 1:13 - loss: 1.1033 - acc: 0.312 - ETA: 1:09 - loss: 1.1023 - acc: 0.316 - ETA: 1:06 - loss: 1.1016 - acc: 0.320 - ETA: 1:03 - loss: 1.1020 - acc: 0.318 - ETA: 1:01 - loss: 1.1019 - acc: 0.319 - ETA: 58s - loss: 1.1017 - acc: 0.319 - ETA: 56s - loss: 1.1013 - acc: 0.32 - ETA: 54s - loss: 1.1011 - acc: 0.32 - ETA: 52s - loss: 1.1010 - acc: 0.32 - ETA: 49s - loss: 1.1006 - acc: 0.33 - ETA: 47s - loss: 1.1002 - acc: 0.32 - ETA: 45s - loss: 1.1001 - acc: 0.33 - ETA: 43s - loss: 1.0999 - acc: 0.33 - ETA: 40s - loss: 1.0998 - acc: 0.33 - ETA: 39s - loss: 1.0997 - acc: 0.33 - ETA: 37s - loss: 1.0995 - acc: 0.33 - ETA: 34s - loss: 1.0991 - acc: 0.34 - ETA: 32s - loss: 1.0989 - acc: 0.34 - ETA: 30s - loss: 1.0987 - acc: 0.35 - ETA

"print(history.history.keys())\n# summarize history for accuracy\nplt.plot(history.history['acc'])\nplt.plot(history.history['val_acc'])\nplt.title('model accuracy')\nplt.ylabel('accuracy')\nplt.xlabel('epoch')\nplt.legend(['train', 'test'], loc='upper left')\nplt.show()\n# summarize history for loss\nplt.plot(history.history['loss'])\nplt.plot(history.history['val_loss'])\nplt.title('model loss')\nplt.ylabel('loss')\nplt.xlabel('epoch')\nplt.legend(['train', 'test'], loc='upper left')\nplt.show()"

In [16]:
#import cv2

#for i in range(1):
    #return_value, image = camera.read()
    #cv2.imwrite('opencv'+str(i)+'.jpg', image)




In [22]:
import numpy as np
from keras.preprocessing import image
test_image = image.load_img('C:/Users/Harsh Pande/Desktop/Data Science/nerur.jpg', target_size = (50, 50))
#test_image = test_image.convert("L"
test_image = image.img_to_array(test_image)
#print(test_image.shape)
test_image = np.expand_dims(test_image, axis = 0)
result = model.predict(test_image)



if (result[0][0] > result[0][1]) and (result[0][0] > result[0][2]):
    print("Infant")
if (result[0][1] > result[0][0]) and (result[0][1] > result[0][2]):
    print("Middle")
elif (result[0][2] > result[0][0]) and (result[0][2] > result[0][1]):
    print("Old")
        


print(result)

Middle
[[0. 1. 0.]]
